class ExampleData {
  ExampleData._internal();

  static List<String> images = [
    "https://s2.coinmarketcap.com/static/img/coins/128x128/1.png",
    "https://s2.coinmarketcap.com/static/img/coins/128x128/1027.png",
    "https://s2.coinmarketcap.com/static/img/coins/128x128/2.png",
    "https://s2.coinmarketcap.com/static/img/coins/128x128/1028.png",
    "https://s2.coinmarketcap.com/static/img/coins/128x128/1029.png",
  ];

  static List<Category> data = [
    indices,
    stocks,
    cryptoCurrencies,
    commodities,
    currencies
  ];

  static Category indices = Category(
    title: "Indices",
    subtitle: "subtitle",
    items: List.generate(
      5,
      (index) {
        return CategoryItem(
          title: "",
          articles: [
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "1 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "2 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "3 hours ago",
              sources: "Reuters",
            ),
          ],
          //types: [FilmStripItem, Trending , Others]
          items: [
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
          ],
        );
      },
    ),
  );

  static Category stocks = Category(
    title: "Stocks",
    subtitle: "subtitle",
    items: List.generate(
      5,
      (index) {
        return CategoryItem(
          title: "",
          articles: [
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "1 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "2 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "3 hours ago",
              sources: "Reuters",
            ),
          ],
          //types: [FilmStripItem, Trending , Others]
          items: [
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
          ],
        );
      },
    ),
  );

  static Category cryptoCurrencies = Category(
    title: "CryptoCurrencies",
    subtitle: "subtitle",
    items: List.generate(
      5,
      (index) {
        return CategoryItem(
          title: "",
          articles: [
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "1 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "2 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "3 hours ago",
              sources: "Reuters",
            ),
          ],
          //types: [FilmStripItem, Trending , Others]
          items: [
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
          ],
        );
      },
    ),
  );

  static Category commodities = Category(
    title: 'Commodities',
    subtitle: 'subtitle',
    items: List.generate(
      5,
      (index) {
        return CategoryItem(
          title: "",
          articles: [
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "1 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "2 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "3 hours ago",
              sources: "Reuters",
            ),
          ],
          //types: [FilmStripItem, Trending , Others]
          items: [
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
          ],
        );
      },
    ),
  );

  static Category currencies = Category(
    title: "Currencies",
    subtitle: "subtitle",
    items: List.generate(
      5,
      (index) {
        return CategoryItem(
          title: "",
          articles: [
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "1 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "2 hours ago",
              sources: "Reuters",
            ),
            Article(
              title:
                  "Coinbase Records Major BTC Withdrawal as Bitcoin Price Stands",
              date: "3 hours ago",
              sources: "Reuters",
            ),
          ],
          //types: [FilmStripItem, Trending , Others]
          items: [
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "FilmStripItem",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Commnunity trends",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Highest Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Unusual Volumn",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Gainers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
            Item(
              typeStr: "Losers",
              title: "BITCOIN",
              subtitle: "BITCOIN",
              price: "240",
              imageUrl: images[index % images.length],
              currency: "\$",
              symbolChange: '+${index / 1.2}%',
            ),
          ],
        );
      },
    ),
  );
}

class Category {
  Category({
    required this.title,
    required this.subtitle,
    required this.items,
  });
  String title;
  String? subtitle;
  List<CategoryItem> items;
}

class CategoryItem {
  CategoryItem(
      {required this.title, required this.articles, required this.items});
  String title;
  List<Article> articles;
  List<Item> items;
}

class Article {
  Article({
    required this.title,
    required this.date,
    required this.sources,
  });
  String title;
  String date;
  String sources;
}

class Item {
  Item(
      {required this.typeStr,
      required this.title,
      required this.price,
      required this.subtitle,
      required this.imageUrl,
      required this.currency,
      required this.symbolChange});
  String typeStr; //types: [FilmStripItem, Trending , Others]
  String title;
  String subtitle;
  String price;
  String imageUrl;
  String currency;
  String symbolChange;
}
